@include('popis_posudjenih.layouts.header')
@include('popis_posudjenih.layouts.main')
@include('popis_posudjenih.components.navigation')
@yield('navigation')
@include('popis_posudjenih.forms.create')
@yield('create')
@include('popis_posudjenih.layouts.footer')